# Static reference data extracted from Hourly - Performance Dashboard V2.6.xlsx
# Mapping sheet (351 rows) + BLANKS sheet (42 rows), deduplicated by SkillName
# Targets from Target sheet, latest period (May 2026)

SKILL_TO_LOB = {
    '18574975: US_Hertz_Telus_Element': {'lob': 'International', 'vendor': 'TELUS'},
    '18574977: US_Hertz_Telus_SPOC': {'lob': 'International', 'vendor': 'TELUS'},
    '18574976: US_Hertz_Telus_Fleet_CEI': {'lob': 'International', 'vendor': 'TELUS'},
    '18574978: US_Hertz_Telus_Sales_Overnight': {'lob': 'International', 'vendor': 'TELUS'},
    '20935634: US_Hertz_Delta_247': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '20687271: US_Hertz_VXI_Roadside_TNC': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '20981194: US_Hertz_VXI_Vehicle_Features': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '20981204: US_Hertz_VXI_RoadsideN_Decagon': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '20935519: US_Hertz_VXI_Roadside_Decagon': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '20980968: US_Hertz_VXI_REX_Decagon': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '18574979: US_Hertz_Telus_Fleet_Desk': {'lob': 'International', 'vendor': 'TELUS'},
    '20981018: US_Hertz_VXI_TNC_Decagon': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '18574743: US_Thrifty_Confirmations': {'lob': 'CONFO', 'vendor': 'HERTZ'},
    '20981205: US_Hertz_VXI_RS_Spanish': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '18574742: US_Dollar_Confirmations': {'lob': 'CONFO', 'vendor': 'HERTZ'},
    '35613187: US_Hertz_VXI_Roadside_VSup_TNC': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '20980967: US_Hertz_Telus_REX_Decagon': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '20981017: US_Hertz_Telus_TNC_Decagon': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '35588010: US_Hertz_Telus_RSLite_Decagon': {'lob': 'Roadside Services', 'vendor': 'TELUS'},
    '20980678: US_Hertz_Telus_REX_BOT': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '20935525: US_Hertz_VXI_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '20981203: US_VXI_VC_NCC_Decagon': {'lob': 'Vehicle Control', 'vendor': 'VXI'},
    '29223619: US_SRP_VXI_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '20936216: US_Hertz_VXI_CSCC_ProUpd': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '20935542: US_Hertz_Telus_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '29223618: US_Hertz_Telus_Damage': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35613875: US_Hertz_Telus_TNCCSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '29223620: US_Hertz_Telus_Loyalty1Decagon': {'lob': 'International', 'vendor': 'TELUS'},
    '20981013: US_Hertz_Telus_Points': {'lob': 'International', 'vendor': 'TELUS'},
    '20936215: US_Hertz_Telus_CSCC_ProUpd': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '20935528: US_Hertz_Telus_FNOL_Decagon': {'lob': 'FNOL', 'vendor': 'TELUS'},
    '20981202: US_Telus_VC_NCC_Decagon': {'lob': 'Vehicle Control', 'vendor': 'TELUS'},
    '29223621: US_Hertz_Telus_Loyalty2Decagon': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35613203: US_Hertz_IGT_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35613915: US_SRP_IGT_NCC': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35613916: US_SRP_IGT_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '20936061: US_Hertz_Telus_CAN_REX': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '20980679: US_Hertz_VXI_REX_BOT': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '35614001: US_Hertz_VXI_TNCCSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '35613760: US_Hertz_Telus_Damage_Hub': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35613182: US_Hertz_VXI_CSCC_TNC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '29223617: US_Hertz_VXI_Damage': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '35613181: US_Hertz_Telus_CSCC_TNC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35613188: US_Hertz_IGT_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35613874: US_Hertz_IGT_TNCCSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '20980970: US_Hertz_VXI_CCM_Decagon': {'lob': 'CCM', 'vendor': 'VXI'},
    '20980969: US_Hertz_Telus_CCM_Decagon': {'lob': 'CCM', 'vendor': 'TELUS'},
    '20981195: US_Dollar_VXI_Vehicle_Features': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35613193: US_Dollar_IGT_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '20981196: US_Thrifty_VXI_Vehicle_Feature': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35613190: US_Thrifty_IGT_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '20980985: US_Hertz_VXI_Element': {'lob': 'Fleet Desk', 'vendor': 'VXI'},
    '20935523: US_Hertz_VXI_HRD_Decagon': {'lob': 'HRD', 'vendor': 'VXI'},
    '20980987: US_Hertz_VXI_Wheels': {'lob': 'Fleet Desk', 'vendor': 'VXI'},
    '20980986: US_Hertz_VXI_ElementAccident': {'lob': 'Fleet Desk', 'vendor': 'VXI'},
    '20687416: US_Hertz_VXI_Roadside_VendorCB': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '20687414: US_Telus_IRVC_NCC': {'lob': 'Vehicle Control', 'vendor': 'TELUS'},
    '20935526: US_Hertz_VXI_Sales_Decagon': {'lob': 'Sales', 'vendor': 'VXI'},
    '20935543: US_Hertz_Telus_Sales_Decagon': {'lob': 'Sales', 'vendor': 'TELUS'},
    '20935529: US_Hertz_Telus_Spanish_Decagon': {'lob': 'Languages', 'vendor': 'TELUS'},
    '20935690: US_Hertz_Telus_NetJet': {'lob': 'International', 'vendor': 'TELUS'},
    '20935688: US_Dollar_Telus_CSSD': {'lob': 'International', 'vendor': 'TELUS'},
    '20981178: US_Hertz_VXI_HRDOB_DC': {'lob': 'HRD', 'vendor': 'VXI'},
    '14349203: US_Firefly_Roadside_Emgy': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14349211: US_Firefly_Telus_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14349209: US_Firefly_Telus_CCM': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14348884: US_MM_ALL_NCC': {'lob': 'MultiMonth', 'vendor': 'HERTZ'},
    '16363658: US_Hertz_Roadside_Police': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14333556: US_Hertz_Roadside_Non_Emgy': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14333554: US_Hertz_Roadside_247': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14333485: US_Hertz_REX': {'lob': 'Rental Extensions', 'vendor': 'HERTZ'},
    '14333555: US_Hertz_VXI_Roadside_247': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14333557: US_Hertz_VXI_Roadside_Non_Emgy': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14333486: US_Hertz_VXI_REX': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '16390431: US_Hertz_VXI_TNC': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '16389943: US_Hertz_VXI_EV_ERS': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '16468695: US_VXI_VC_NCC': {'lob': 'Vehicle Control', 'vendor': 'VXI'},
    '14333548: US_Hertz_VXI_CC_Auth': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '14355110: US_Hertz_VXI_Vehicle_Control': {'lob': 'Vehicle Control', 'vendor': 'VXI'},
    '16390518: US_Hertz_VXI_Roadside_Fre': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '16390249: US_Hertz_VXI_EmployDiscount': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '20980937: US_Domestic_DataBreach': {'lob': 'International', 'vendor': 'TELUS'},
    '20935711: US_Hertz_Telus_Field_PID': {'lob': 'International', 'vendor': 'TELUS'},
    '20981207: US_Dollar_VXI_RS_Spanish': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '20980677: US_Dollar_VXI_REX_SelfServ': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '20981183: US_Hertz_VXI_HRD_SPOC': {'lob': 'HRD', 'vendor': 'VXI'},
    '35613191: US_Thrifty_IGT_CSCC_Blue': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '20980984: US_Hertz_VXI_Fleet_Desk': {'lob': 'Fleet Desk', 'vendor': 'VXI'},
    '14349216: US_Firefly_VXI_CCM': {'lob': 'CCM', 'vendor': 'VXI'},
    '35613197: US_Hertz_IGT_CS_Platinum': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35613194: US_Dollar_IGT_CSCC_Express': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '14349213: US_Firefly_Telus_REX': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '20981208: US_Thrifty_VXI_RS_Spanish': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35613121: US_Hertz_HRD_TNC_Conv_Outbound': {'lob': 'HRD', 'vendor': 'HERTZ'},
    '14349202: US_Firefly_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '16468419: US_Hertz_Telus_Uber_CA_EN': {'lob': 'International', 'vendor': 'TELUS'},
    '14349220: US_Firefly_VXI_REX': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '20936010: US_Hertz_SPOC_BizTvlr': {'lob': 'SPOC', 'vendor': 'HERTZ'},
    '20845309: US_Hertz_Fractional_AirPartner': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '16390430: US_Hertz_Telus_TNC': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '14333549: US_Hertz_Telus_CC_Auth': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '16468694: US_Telus_VC_NCC': {'lob': 'Vehicle Control', 'vendor': 'TELUS'},
    '14355109: US_Hertz_Telus_Vehicle_Control': {'lob': 'Vehicle Control', 'vendor': 'TELUS'},
    '14333487: US_Hertz_Telus_REX': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '16390248: US_Hertz_Telus_EmployDiscount': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '14333491: US_Hertz_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '16389977: US_VC_IR_NCC': {'lob': 'Vehicle Control', 'vendor': 'HERTZ'},
    '14355442: US_Hertz_CSCC_Gold': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '16468870: US_Hertz_CSCC_ComBill': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14333523: US_Hertz_ECS': {'lob': 'Executive Customer Services', 'vendor': 'HERTZ'},
    '14348908: US_VC_NCC': {'lob': 'Vehicle Control', 'vendor': 'HERTZ'},
    '16363659: US_SRP_VXI_NCC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14333513: US_Hertz_VXI_First_Choice': {'lob': 'Fleet Desk', 'vendor': 'VXI'},
    '14333492: US_Hertz_VXI_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14355444: US_Hertz_VXI_CSCC_Gold': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14333493: US_Hertz_Telus_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '16390447: US_Hertz_Telus_CS_Platinum': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '16468871: US_Hertz_Telus_CSCC_ComBill': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '18574222: US_Hertz_Telus_EV_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14333546: US_Hertz_FNOL': {'lob': 'FNOL', 'vendor': 'TELUS'},
    '16390446: US_Hertz_Telus_CS_PC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14333472: US_Hertz_CCM_Intl': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14333475: US_Hertz_CCM': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14349245: US_Hertz_AnswerLink': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14333506: US_Hertz_CCM_Gold': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14333476: US_Hertz_VXI_CCM': {'lob': 'CCM', 'vendor': 'VXI'},
    '14349786: US_Hertz_VXI_AAA_CCM': {'lob': 'CCM', 'vendor': 'VXI'},
    '14333473: US_Hertz_VXI_CCM_Intl': {'lob': 'International', 'vendor': 'VXI'},
    '14333507: US_Hertz_VXI_CCM_Gold': {'lob': 'CCM', 'vendor': 'VXI'},
    '14349787: US_Hertz_Telus_AAA_CCM': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14333508: US_Hertz_Telus_CCM_Gold': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14333477: US_Hertz_Telus_CCM': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14349795: US_Hertz_Telus_CCM Spanish': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14333474: US_Hertz_Telus_CCM_Intl': {'lob': 'International', 'vendor': 'TELUS'},
    '14339441: US_Hertz_Telus_CCM_Intl_Gold': {'lob': 'International', 'vendor': 'TELUS'},
    '14339803: US_Dollar_Roadside_Emgy': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '16390054: US_Dollar_Roadside_Police': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14348845: US_Dollar_VXI_Roadside_247': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14348847: US_Dollar_VXI_Roadside_Non_Emg': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14339801: US_Dollar_VXI_REX': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '14339802: US_Dollar_Telus_REX': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '14355439: US_Dollar_CSCC_Express': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14339806: US_Dollar_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14339807: US_Dollar_VXI_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14355441: US_Dollar_VXI_CSCC_Express': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14348838: US_Dollar_VXI_First_Choice': {'lob': 'Fleet Desk', 'vendor': 'VXI'},
    '14339808: US_Dollar_Telus_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14355440: US_Dollar_Telus_CSCC_Express': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14339788: US_Dollar_CCM_Intl': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14339792: US_Dollar_VXI_CCM': {'lob': 'CCM', 'vendor': 'VXI'},
    '14348832: US_Dollar_VXI_CCM_Express': {'lob': 'CCM', 'vendor': 'VXI'},
    '14339793: US_Dollar_Telus_CCM': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14348833: US_Dollar_Telus_CCM_Express': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14348938: US_Thrifty_REX': {'lob': 'Rental Extensions', 'vendor': 'HERTZ'},
    '14348950: US_Thrifty_Roadside_247': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '16390055: US_Thrifty_Roadside_Police': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14348980: US_Thrifty_VXI_Roadside_247': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14348971: US_Thrifty_VXI_REX': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '14348981: US_Thrifty_VXI_Roadside_Non_Em': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14348957: US_Thrifty_Telus_REX': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '14349252: US_Hertz_CS_Platinum': {'lob': 'Executive Customer Services', 'vendor': 'HERTZ'},
    '16390451: US_Hertz_VXI_EmployDiscount2': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14355443: US_Hertz_Telus_CSCC_Gold': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14348846: US_Dollar_Roadside_Non_Emgy': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14339790: US_Dollar_Telus_CCM_Intl': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14349219: US_Firefly_VXI_Roadside_Emgy': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14339800: US_Dollar_REX': {'lob': 'Rental Extensions', 'vendor': 'HERTZ'},
    '14339791: US_Dollar_CCM': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14339789: US_Dollar_VXI_CCM_Intl': {'lob': 'CCM', 'vendor': 'VXI'},
    '14349800: US_Hertz_EV_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14348851: US_Dollar_VXI_CCM_Intl_Express': {'lob': 'CCM', 'vendor': 'VXI'},
    '14348939: US_Thrifty_Roadside_Emgy': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '16390450: US_Hertz_Telus_EmployDiscount2': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14348844: US_Dollar_Roadside_247': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14333503: US_Hertz_CCM_Intl_Gold': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14339439: US_Hertz_VXI_CCM_Intl_Gold': {'lob': 'International', 'vendor': 'VXI'},
    '14348940: US_Thrifty_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14355445: US_Thrifty_CSCC_Blue': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14348973: US_Thrifty_VXI_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '16390344: US_SRP_Escalations': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14348831: US_Dollar_CCM_Express': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14348959: US_Thrifty_Telus_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14355446: US_Thrifty_Telus_CSCC_Blue': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '14348934: US_Thrifty_CCM_Intl': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14348935: US_Thrifty_CCM': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14348968: US_Thrifty_VXI_CCM': {'lob': 'CCM', 'vendor': 'VXI'},
    '14348976: US_Thrifty_VXI_CCM_Blue': {'lob': 'CCM', 'vendor': 'VXI'},
    '14348954: US_Thrifty_Telus_CCM': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14333552: US_Hertz_VXI_HRD': {'lob': 'HRD', 'vendor': 'VXI'},
    '16468412: US_Hertz_VXI_HRD_Callback': {'lob': 'HRD', 'vendor': 'VXI'},
    '18574268: US_Hertz_Telus_BodyShop': {'lob': 'Damage', 'vendor': 'TELUS'},
    '14333516: US_Hertz_BRST': {'lob': 'BRST', 'vendor': 'HERTZ'},
    '16363533: US_Hertz_Netjet': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14333512: US_Hertz_CSSD': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14333517: US_Hertz_Confirmations': {'lob': 'CONFO', 'vendor': 'HERTZ'},
    '14333524: US_Hertz_Sales_Platinum': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14333479: US_Hertz_Sales_Intl': {'lob': 'International', 'vendor': 'HERTZ'},
    '14333483: US_Hertz_VXI_Sales': {'lob': 'Sales', 'vendor': 'VXI'},
    '14333501: US_Hertz_VXI_Sales_Gold': {'lob': 'Sales', 'vendor': 'VXI'},
    '14355260: US_Hertz_VXI_Market_Xfer': {'lob': 'Sales', 'vendor': 'VXI'},
    '14349784: US_Hertz_VXI_AAA_Sales': {'lob': 'Sales', 'vendor': 'VXI'},
    '14333480: US_Hertz_VXI_Sales_Intl': {'lob': 'International', 'vendor': 'VXI'},
    '14333537: US_Hertz_VXI_Sales_PC': {'lob': 'Sales', 'vendor': 'VXI'},
    '16468423: US_Hertz_Telus_CSSD': {'lob': 'International', 'vendor': 'TELUS'},
    '14349788: US_Hertz_Telus_AAA_Premier': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14333536: US_Hertz_Telus_Sales_PC': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14339764: US_Hertz_Telus_USAA': {'lob': 'International', 'vendor': 'TELUS'},
    '14349785: US_Hertz_Telus_AAA_Sales': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14333484: US_Hertz_Telus_Sales': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14355261: US_Hertz_Telus_Market_Xfer': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14349251: US_Hertz_Telus_French': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14333525: US_Hertz_Telus_Sales_Platinum': {'lob': 'International', 'vendor': 'TELUS'},
    '14355124: US_Hertz_Telus_Sales Spanish': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14349789: US_Hertz_Telus_AAA_Breakdown': {'lob': 'Sales', 'vendor': 'TELUS'},
    '16468204: US_Hertz_Telus_Fractional': {'lob': 'International', 'vendor': 'TELUS'},
    '14333481: US_Hertz_Telus_Sales_Intl': {'lob': 'International', 'vendor': 'TELUS'},
    '14333502: US_Hertz_Telus_Sales_Gold': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14339798: US_Dollar_VXI_Sales': {'lob': 'Sales', 'vendor': 'VXI'},
    '14348826: US_Dollar_VXI_Sales_Express': {'lob': 'Sales', 'vendor': 'VXI'},
    '14339799: US_Dollar_Telus_Sales': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14349458: US_Dollar_Telus_Spanish': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14349459: US_Dollar_Telus_French': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14348827: US_Dollar_Telus_Sales_Express': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14348970: US_Thrifty_VXI_Sales': {'lob': 'Sales', 'vendor': 'VXI'},
    '14348975: US_Thrifty_VXI_Sales_Blue': {'lob': 'Sales', 'vendor': 'VXI'},
    '14349456: US_Thrifty_Telus_Spanish': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14348956: US_Thrifty_Telus_Sales': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14349444: US_Thrifty_Spanish_Tour_Desk': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14349457: US_Thrifty_Telus_French': {'lob': 'Languages', 'vendor': 'TELUS'},
    '14333478: US_Hertz_HRD': {'lob': 'HRD', 'vendor': 'HERTZ'},
    '14333530: US_Hertz_Element': {'lob': 'Fleet Desk', 'vendor': 'HERTZ'},
    '14333527: US_Hertz_Fleet_Desk': {'lob': 'Fleet Desk', 'vendor': 'HERTZ'},
    '14333533: US_Hertz_Fleet_CEI': {'lob': 'Fleet Desk', 'vendor': 'HERTZ'},
    '14333540: US_Hertz_SPOC_SF': {'lob': 'SPOC', 'vendor': 'HERTZ'},
    '18574212: US_Hertz_Fleet_Donlen_Wheels': {'lob': 'Fleet Desk', 'vendor': 'HERTZ'},
    '14333534: US_Hertz_Nationwide': {'lob': 'Fleet Desk', 'vendor': 'HERTZ'},
    '16363807: US_Hertz_SPOC_Counter': {'lob': 'SPOC', 'vendor': 'HERTZ'},
    '16362857: US_Hertz_ERS_Outbound': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '16362858: US_Hertz_VXI_ERS_Outbound': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '16468413: US_Hertz_VXI_HRD_Outbound': {'lob': 'HRD', 'vendor': 'VXI'},
    '18574269: US_Hertz_Telus_BS_Outbound': {'lob': 'Damage', 'vendor': 'TELUS'},
    '14354930: US_Hertz_HRD_Outbound': {'lob': 'HRD', 'vendor': 'HERTZ'},
    '20980676: US_Dollar_Telus_REX_SelfServ': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '14348953: US_Thrifty_Telus_CCM_Intl': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14333522: US_Hertz_Telus_Uber_CA_FR': {'lob': 'Languages', 'vendor': 'TELUS'},
    '16390517: US_Hertz_Roadside_Fre': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14348962: US_Thrifty_Telus_CCM_Blue': {'lob': 'CCM', 'vendor': 'TELUS'},
    '14349223: US_Firefly_VXI_Sales': {'lob': 'Sales', 'vendor': 'VXI'},
    '16468252: US_Hertz_Fractional_Sentient': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14333521: US_Hertz_Uber_CA_EN': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '16468253: US_Hertz_Fractional_Wheelsup': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14349441: US_Dollar_BRST': {'lob': 'BRST', 'vendor': 'HERTZ'},
    '14348961: US_Thrifty_Telus_Sales_Blue': {'lob': 'Sales', 'vendor': 'TELUS'},
    '20980672: US_Thrifty_Telus_REX_SelfServ': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '14348951: US_Thrifty_Roadside_Non_Emgy': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14355447: US_Thrifty_VXI_CSCC_Blue': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14348967: US_Thrifty_VXI_CCM_Intl': {'lob': 'CCM', 'vendor': 'VXI'},
    '14349214: US_Firefly_Telus_Sales': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14339437: US_Hertz_Telus_Sales_Intl_Gold': {'lob': 'International', 'vendor': 'TELUS'},
    '14339795: US_Dollar_VXI_Sales_Intl': {'lob': 'Sales', 'vendor': 'VXI'},
    '14348850: US_Dollar_Telus_Sales_Intl_Exp': {'lob': 'Sales', 'vendor': 'TELUS'},
    '14348978: US_Thrifty_VXI_First_Choice': {'lob': 'Fleet Desk', 'vendor': 'VXI'},
    '16389951: US_Hertz_VXI_PleasantHolidays': {'lob': 'Sales', 'vendor': 'VXI'},
    '20936062: US_Hertz_VXI_CAN_REX': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '14339796: US_Dollar_Telus_Sales_Intl': {'lob': 'Sales', 'vendor': 'TELUS'},
    '20980680: US_Dollar_Telus_REX_BOT': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '14333532: US_Hertz_Element_OF_ERS': {'lob': 'Fleet Desk', 'vendor': 'HERTZ'},
    '14348837: US_Dollar_CSSD': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14348969: US_Thrifty_VXI_Sales_Intl': {'lob': 'Sales', 'vendor': 'VXI'},
    '14355084: US_Hertz_SF_Licensee': {'lob': '', 'vendor': 'HERTZ'},
    '16390519: US_Thrifty_VXI_Roadside_Fre': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35613204: US_Hertz_IGT_CSCC_ProUpd': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35613186: US_Hertz_VXI_RoadsideEvent_TNC': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '14348852: US_Dollar_VXI_Sales_Intl_Expre': {'lob': 'Sales', 'vendor': 'VXI'},
    '14339438: US_Hertz_VXI_Sales_Intl_Gold': {'lob': 'International', 'vendor': 'VXI'},
    '18574507: US_Hertz_VXI_RS_Triage1': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '16390520: US_Thrifty_Roadside_Fre': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14333547: US_Hertz_CC_Auth': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14349801: US_Hertz_CSCC_Field_PID': {'lob': 'Billing/Disputes', 'vendor': 'HERTZ'},
    '14348849: US_Dollar_Telus_CCM_Intl_Expre': {'lob': 'CCM', 'vendor': 'TELUS'},
    '16389952: US_Hertz_Telus_PleasantHoliday': {'lob': 'Sales', 'vendor': 'TELUS'},
    '16468872: US_Hertz_VXI_CSCC_ComBill': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '18574221: US_Hertz_VXI_EV_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14333531: US_Hertz_Element_OF_HRD': {'lob': 'Fleet Desk', 'vendor': 'HERTZ'},
    '35613201: US_Hertz_IGT_EV_Usability_SS': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '20935689: US_Thrifty_Telus_CSSD': {'lob': 'International', 'vendor': 'TELUS'},
    '35613198: US_Hertz_IGT_CSCC_ComBill': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '18574223: US_Hertz_Telus_EV_Usability_SS': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35613206: US_Hertz_IGT_Damage': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '14349797: US_Hertz_EV_ERS': {'lob': 'Roadside Services', 'vendor': 'HERTZ'},
    '14349218: US_Firefly_VXI_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '16390250: US_Hertz_EmployDiscount': {'lob': 'Rental Extensions', 'vendor': 'HERTZ'},
    '14348944: US_Thrifty_CCM_Blue': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '14349792: US_Hertz_AAA_CCM': {'lob': 'CCM', 'vendor': 'HERTZ'},
    '35613196: US_Hertz_IGT_CS_PC': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '14333538: US_Hertz_CS_PC': {'lob': 'Executive Customer Services', 'vendor': 'HERTZ'},
    '35613195: US_Hertz_IGT_EmployDiscount2': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35588010: US_Hertz_VXI_RSLite_Decagon': {'lob': 'Roadside Lite', 'vendor': 'VXI'},
    '14333550: US_Hertz_Operations': {'lob': 'OPERATIONS', 'vendor': 'HERTZ'},
    '14333482: US_Hertz_Sales': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14333500: US_Hertz_Sales_Gold': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14348848: US_Dollar_Sales_Intl_Express': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '14348936: US_Thrifty_Sales_Intl': {'lob': 'Sales', 'vendor': 'HERTZ'},
    '35638266: US_Hertz_Telus_Expedia_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35638260: US_Hertz_Telus_Expedia_CCM': {'lob': 'CCM', 'vendor': 'TELUS'},
    '35638689: US_Dollar_VXI_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '35638688: US_Dollar_Telus_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35638695: US_Dollar_Telus_Loyalty_Deca': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35638716: US_Thrifty_VXI_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '35638728: US_Thrifty_VXI_Roadside_NE_Dec': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35638719: US_Thrifty_Telus_Sales_Decagon': {'lob': 'Sales', 'vendor': 'TELUS'},
    '35638699: US_Dollar_VXI_Roadside_Decagon': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35638697: US_Dollar_Telus_VC_NCC_Decagon': {'lob': 'Vehicle Control', 'vendor': 'TELUS'},
    '35638693: US_Dollar_VXI_Sales_Decagon': {'lob': 'Sales', 'vendor': 'VXI'},
    '35638692: US_Dollar_Telus_Sales_Decagon': {'lob': 'Sales', 'vendor': 'TELUS'},
    '35638264: US_Hertz_VXI_Expedia_Roadside': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35638702: US_Dollar_SRP_IGT_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35638684: US_Dollar_Telus_CCM_Decagon': {'lob': 'CCM', 'vendor': 'TELUS'},
    '35638715: US_Thrifty_Telus_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35638691: US_Dollar_VXI_REX_Decagon': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '35638717: US_Thrifty_Telus_REX_Decagon': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '20980670: US_Hertz_Telus_REX_SelfService': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '35638267: US_Hertz_VXI_Expedia_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '35638265: US_Hertz_IGT_Expedia_CSCC': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35613183: US_Hertz_IGT_CSCC_TNC': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35638703: US_Dollar_SRP_VXI_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '35638685: US_Dollar_VXI_CCM_Decagon': {'lob': 'CCM', 'vendor': 'VXI'},
    '35638722: US_Thrifty_Telus_Loyalty_Deca': {'lob': 'Billing/Disputes', 'vendor': 'TELUS'},
    '35638730: US_Thrifty_SRP_IGT_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35638712: US_Thrifty_VXI_CCM_Decagon': {'lob': 'CCM', 'vendor': 'VXI'},
    '35638694: US_Dollar_Telus_SPN_Decagon': {'lob': 'Languages', 'vendor': 'TELUS'},
    '35638720: US_Thrifty_VXI_Sales_Decagon': {'lob': 'Sales', 'vendor': 'VXI'},
    '35638711: US_Thrifty_Telus_CCM_Decagon': {'lob': 'CCM', 'vendor': 'TELUS'},
    '35638727: US_Thrifty_VXI_Roadside_Decago': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35638718: US_Thrifty_VXI_REX_Decagon': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '35638698: US_Dollar_VXI_VC_NCC_Decagon': {'lob': 'Vehicle Control', 'vendor': 'VXI'},
    '35638725: US_Thrifty_Telus_VC_NCC_Decago': {'lob': 'Vehicle Control', 'vendor': 'TELUS'},
    '35638690: US_Dollar_Telus_REX_Decagon': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '35638721: US_Thrifty_Telus_SPN_Decagon': {'lob': 'Languages', 'vendor': 'TELUS'},
    '35638700: US_Dollar_VXI_Roadside_NE_Dec': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35638701: US_Dollar_VXI_RSLite_Decagon': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35638729: US_Thrifty_VXI_RSLite_Decagon': {'lob': 'Roadside Services', 'vendor': 'VXI'},
    '35638731: US_Thrifty_SRP_VXI_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'VXI'},
    '14349810: US_Hertz_Operations_Home_Agent': {'lob': 'OPERATIONS', 'vendor': 'HERTZ'},
    '20980671: US_Hertz_VXI_REX_SelfService': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '35638263: US_Hertz_VXI_Expedia_REX': {'lob': 'Rental Extensions', 'vendor': 'VXI'},
    '35638262: US_Hertz_Telus_Expedia_REX': {'lob': 'Rental Extensions', 'vendor': 'TELUS'},
    '35638261: US_Hertz_VXI_Expedia_CCM': {'lob': 'CCM', 'vendor': 'VXI'},
    '35638687: US_Dollar_IGT_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35638714: US_Thrifty_IGT_CSCC_Decagon': {'lob': 'Billing/Disputes', 'vendor': 'IGT'},
    '35613185: US_Hertz_VXI_VC_TNC': {'lob': 'Vehicle Control', 'vendor': 'VXI'},
}

# Targets per LOB — May 2026 (most recent period in Target sheet)
# Keys: aht (seconds), asa (seconds), abn (ratio 0–1)
TARGETS = {
    'Sales': {'aht': 362, 'asa': 13, 'abn': 0.03},
    'CCM': {'aht': 312, 'asa': 120, 'abn': 0.03},
    'International': {'aht': 415, 'asa': 47, 'abn': 0.03},
    'CSCC': {'aht': 538, 'asa': 220, 'abn': 0.10},
    'Billing/Disputes': {'aht': 538, 'asa': 220, 'abn': 0.10},
    'Damage': {'aht': 540, 'asa': 19, 'abn': 0.03},
    'Rental Extensions': {'aht': 331, 'asa': 140, 'abn': 0.03},
    'MultiMonth': {'aht': 414, 'asa': 363, 'abn': 0.03},
    'Vehicle Control': {'aht': 345, 'asa': 53, 'abn': 0.10},
    'Roadside Services': {'aht': 700, 'asa': 258, 'abn': 0.14},
    'Languages': {'aht': 369, 'asa': 120, 'abn': 0.03},
    'FNOL': {'aht': 273, 'asa': 182, 'abn': 0.03},
    'CONFO': {'aht': 377, 'asa': 5, 'abn': 0.03},
    'First Choice Offered': {'aht': 252, 'asa': 19, 'abn': 0.02},
    'Executive Customer Services': {'aht': 448, 'asa': 22, 'abn': 0.02},
    'HRD': {'aht': 277, 'asa': 9, 'abn': 0.03},
    'Fleet Desk': {'aht': 385, 'asa': 19, 'abn': 0.02},
    'SPOC': {'aht': 229, 'asa': 10, 'abn': 0.02},
    'BRST': {'aht': 143, 'asa': 10, 'abn': 0.10},
    'Roadside Lite': {'aht': 605, 'asa': 10, 'abn': 0.06},
}

DEFAULT_TARGET = {'aht': 400, 'asa': 30, 'abn': 0.05}

LOB_DISPLAY_ORDER = [
    'Sales', 'CCM', 'Rental Extensions', 'Roadside Services', 'International',
    'FNOL', 'HRD', 'Vehicle Control', 'Fleet Desk', 'Languages', 'MultiMonth',
    'SPOC', 'BRST', 'Executive Customer Services', 'Damage', 'CONFO',
    'Billing/Disputes', 'First Choice Offered', 'Roadside Lite', 'OPERATIONS',
]

VENDORS = ['TELUS', 'VXI', 'IGT', 'HERTZ']
